/** Built-in "Most likely to..." prompts, team/office flavoured and SFW. */
export const MOST_LIKELY_PROMPTS: string[] = [
  "reply-all to a company-wide email by accident",
  "become a millionaire from a side project",
  "show up to a meeting in pyjamas",
  "survive the longest in a zombie apocalypse",
  "accidentally leave themselves on mute the entire call",
  "start a podcast no one asked for",
  "forget their own birthday",
  "get lost in their own neighbourhood",
  "win a reality TV show",
  "adopt five pets in one weekend",
  "send a text to the wrong group chat",
  "become a famous influencer",
  "cry during a Pixar movie",
  "fall asleep at their desk after lunch",
  "talk their way out of a speeding ticket",
  "bring snacks for the whole team unprompted",
  "accidentally like a 3-year-old photo while stalking online",
  "go viral for something embarrassing",
  "become the boss one day",
  "spend their whole paycheck on coffee",
  "still be using the same phone in five years",
  "plan the best team holiday party",
  "get way too competitive at board games",
  "know every lyric to a 2000s pop song",
  "accidentally call their boss 'mum' or 'dad'",
  "take the most photos on a group trip",
  "have a secret talent no one knows about",
  "be late to their own wedding",
  "binge an entire TV series in one night",
  "start talking to strangers in the elevator",
  "forget where they parked the car",
  "win an award for 'most enthusiastic'",
];
